name: Saeeda Gulzari Photography
favicon: null
layout_spectrum: 0.9601269187405705
typography_spectrum: 0.2454486412461847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.14937986247241497
  lightness: 0.47513683163560927
  saturation: 0.058770252391695976
  rhythmicContrast: 0.883138770237565
purpose: []
